### ISSUE TITLE
MouseDown時のコード修正案

### ISSUE THREAD

**Issue by Qamada** [Kuwayoshi/DrawRectangle#1]
おそらく下記の様に修正すべきかと。

・修正前（現在）
        private void drawCanvas_MouseDown(object sender, MouseButtonEventArgs e)
        {
（中略）
            Canvas.SetLeft(this.currentRect, clickPoint.X);
            Canvas.SetTop(this.currentRect, clickPoint.X);
（中略）
        }

・修正後（例）
        private void drawCanvas_MouseDown(object sender, MouseButtonEventArgs e)
        {
（中略）
            Canvas.SetLeft(this.currentRect, clickPoint.X);
            Canvas.SetTop(this.currentRect, clickPoint.Y);
（中略）
        }

**Comment by Kuwayoshi** [comment]
ご指摘ありがとうございます。修正しました。
